add backend tests to pipeline

diff --git a/.github/workflows/test_build.yml b/.github/workflows/test_build.yml
--- a/.github/workflows/test_build.yml
+++ b/.github/workflows/test_build.yml
@@ -34,3 +34,13 @@ jobs:
           else
             echo "Pattern 'FAIL' not found in frontend test results."
           fi
+      - name: Run backend Tests
+        run: |
+          docker-compose -f docker-compose.yml exec -T web python manage.py run_tests | tee tests_output.txt # Run tests
+
+          if grep -q "FAILED tests" tests_output.txt; then
+            echo "Pattern 'FAILED tests' found in test results. Exiting with code 1."
+            exit 1
+          else
+            echo "Pattern 'FAILED tests' not found in test results."
+          fi
