add frontend tests to pipeline

diff --git a/.github/workflows/test_build.yml b/.github/workflows/test_build.yml
--- a/.github/workflows/test_build.yml
+++ b/.github/workflows/test_build.yml
@@ -23,3 +23,14 @@ jobs:
 
       - name: Delay for 3 seconds before running tests
         run: sleep 3
+
+      - name: Run frontend tests
+        run: |
+          docker exec react-frontend npm run test | tee frontend_tests_output.txt
+
+          if grep -q "failed" frontend_tests_output.txt; then
+            echo "Pattern 'failed' found in frontend test results. Exiting with code 1."
+            exit 1
+          else
+            echo "Pattern 'failed' not found in frontend test results."
+          fi
